services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=youtube
    volumes:
      - ~/.aspnet/https:/https
    networks:
      - global_network
    ports:
      - 8080:8080
      - 8081:8081
networks:
  global_network:
    external: true
